enum FormScreens {
  CREDIT_CARD_DETAILS = 'CREDIT_CARD_DETAILS',
  DELIVERY_MODE = 'DELIVERY_MODE',
  FORM_SUBMISSION = 'FORM_SUBMISSION',
  PAYMENT_METHOD = 'PAYMENT_METHOD',
  PERSONAL_DETAILS = 'PERSONAL_DETAILS',
}

export default FormScreens;
