enum FormScreens {
  CREDIT_CARD_DETAILS = 'CREDIT_CARD_DETAILS',
  COURIER_DELIVERY_DETAILS = 'COURIER_DELIVERY_DETAILS',
  DELIVERY_MODE = 'DELIVERY_MODE',
  PAYMENT_METHOD = 'PAYMENT_METHOD',
  PERSONAL_DETAILS = 'PERSONAL_DETAILS',
}

export default FormScreens;
