// TODO: Remove substeps
enum ScreensOrder {
  PERSONAL_DETAILS,
  DELIVERY_MODE,
  COURIER_DELIVERY_DETAILS,
  POST_DELIVERY_DETAILS,
  PAYMENT_METHOD,
  CREDIT_CARD_DETAILS,
  FORM_SUBMISSION,
  FORM_SUCCESS,
}

export default ScreensOrder;
